apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdelt-frontend
  namespace: gdelt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdelt-frontend
  template:
    metadata:
      labels:
        app: gdelt-frontend
    spec:
      containers:
        - name: gdelt-frontend
          image: ghcr.io/ivan-artemev-dev/frontend:latest
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
