apiVersion: batch/v1
kind: CronJob
metadata:
  name: gdelt-pipeline
  namespace: gdelt
spec:
  schedule: "*/20 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: gdelt-pipeline
              image: ghcr.io/ivan-artemev-dev/parse_gdelt:latest
              resources:
                requests:
                  cpu: "200m"
                  memory: "256Mi"
                limits:
                  cpu: "500m"
                  memory: "512Mi"
              envFrom:
                - configMapRef:
                    name: gdelt-config
          restartPolicy: OnFailure