apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdelt-pipeline
  namespace: gdelt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdelt-pipeline
  template:
    metadata:
      labels:
        app: gdelt-pipeline
    spec:
      containers:
        - name: gdelt-pipeline
          image: localhost:5000/gdelt-pipeline:v1.0
          env:
            - name: ES_HOST
              value: http://elasticsearch:9200
