apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdelt-backend
  namespace: gdelt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdelt-backend
  template:
    metadata:
      labels:
        app: gdelt-backend
    spec:
      containers:
        - name: gdelt-backend
          image: ghcr.io/ivan-artemev-dev/backend:latest
          ports:
            - containerPort: 8099
          resources:
            requests:
              cpu: "100m"
              memory: "150Mi"
            limits:
              cpu: "300m"
              memory: "300Mi"
          envFrom:
            - configMapRef:
                name: gdelt-config
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8099
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8099
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3