apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdelt-backend
  namespace: gdelt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdelt-backend
  template:
    metadata:
      labels:
        app: gdelt-backend
    spec:
      containers:
        - name: gdelt-backend
          image: ghcr.io/ivan-artemev-dev/backend:latest
          ports:
            - containerPort: 8099
          env:
            - name: ELASTIC_URL
              value: http://elasticsearch:9200
            - name: ELASTIC_INDEX
              value: gdelt_gkg
            - name: BACKEND_HOST
              value: 0.0.0.0
            - name: BACKEND_PORT
              value: "8099"
