apiVersion: v1
kind: Service
metadata:
  name: gdelt-backend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: gdelt-backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
  type: ClusterIP
