apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.elasticsearch.storage }}
        storageClassName: {{ .Values.elasticsearch.storageClassName }}
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: elasticsearch
          image: "{{ .Values.elasticsearch.image }}:{{ .Values.elasticsearch.tag }}"
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
            - name: ES_JAVA_OPTS
              value: {{ .Values.elasticsearch.javaOpts | quote }}
          resources:
            requests:
              cpu: {{ .Values.elasticsearch.resources.requests.cpu | quote }}
              memory: {{ .Values.elasticsearch.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.elasticsearch.resources.limits.cpu | quote }}
              memory: {{ .Values.elasticsearch.resources.limits.memory | quote }}
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data