version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  gdelt-pipeline:
    build: ./parse_gdelt
    container_name: gdelt-pipeline
    environment:
      - ES_HOST=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    volumes:
      - ./parse_gdelt/downloads:/app/downloads

volumes:
  es_data:
