services:
  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  gdelt-pipeline:
    build: ./parse_gdelt
    container_name: gdelt-pipeline
    environment:
      - ES_HOST=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    volumes:
      - ./parse_gdelt/downloads:/app/downloads

  gdelt-backend:
    build: ./gdelt_dashboard/backend
    container_name: gdelt-backend
    environment:
      - ELASTIC_URL=http://elasticsearch:9200
      - ELASTIC_INDEX=gdelt_gkg
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8099
    ports:
      - "8099:8099"
    depends_on:
      - elasticsearch

  gdelt-frontend:
    build: ./gdelt_dashboard/frontend
    container_name: gdelt-frontend
    ports:
      - "80:80"
    depends_on:
      - gdelt-backend

volumes:
  es_data:
